# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  #  pull_request:
  #    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        default: 'qa'
      browser:
        description: 'Choose the browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
      cucumberTags:
        description: 'Optional Cucumber tag filter (e.g., @user)'
        required: false

      threadCount:
        description: 'Optional thread count (e.g., 3)'
        required: false


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '137.0.7151.119' # Match to Chrome version

      - name: Install xvfb for GUI support
        run: sudo apt-get install -y xvfb


      - name: Build with Maven
        run: |
          
          export DISPLAY=:99
          
          TAGS= ${{github.event.inputs.cucumberTags}}
          THREAD-COUNT = ${{github.event.inputs.threadCount}}
          
          ARGS = ""
          if [[ -n \"$TAGS\" ]]; then
            ARGS= '$ARGS -Dcucumber.filter.tags=$TAGS'
          fi

          if [[ -n \"$THREADS\" ]]; then
              ARGS ="$ARGS -DthreadCount=THREAD-COUNT\"
          fi
          
          echo "Running: xvfb-run -a mvn test $ARGS"
          xvfb-run -a mvn test $ARGS || true

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-html-reports/